### ISSUE TITLE
Choosing source opens second actor window

### ISSUE THREAD

**Issue by mad4linux** [GreenDelta/olca-app#10]
---

EDIT: Today, we,ve updated our system to OS X 10.11. And although I could trigger the bug once by clicking around like mad, it seems that it doesn't happen anymore in daily use. So this bug may be closed, because it just happens on a distinct combination of OS and openLCA.

The bug described below was happening on OS X 10.9 with openLCA 1.4.1:

---

This Bug happens always when trying to insert both a data documentor and a data generator to a process on the administrative Information tab. It also happens often when inserting a publication source subsequently. I'm running openLCA 1.4.1, mac version.

Steps to reproduce:
- Open a process
- Go to the Administrative information tab
- Klick on the Actor sign next to the data generator field or the data documentor field
- Choose an actor an klick ok (everything fine up to this point)
- Now klick on the Actor sign next to either the data generator field or the data documentor field, whichever is still empty
- Select an actor entry from the list
- a second actor window opens (expected behaviour would be to have the actor selected on the list)
  The same behaviour happens sometimes when trying to select a publication right after selecting the two actors. 

![bildschirmfoto 2015-10-27 um 08 35 29](https://cloud.githubusercontent.com/assets/1000057/10752043/0111fae0-7c86-11e5-929a-d27128d4ea32.png)

After closing the second window, the GUI update seems somehow broken. You will have to klick the actor name and OK button twice. Also saving right afterwards seems to take ages unless you klick the save button twice. After saving the dataset, the GUI behaves normally again.

**Comment by mad4linux** [comment]
Just a small additiion to the description: It actually doesn't matter where you click in the actor window when the bug triggers. A klick anywhere will open a second actor window.

**Comment by msrocka** [comment]
@mad4linux is this still an issue in openLCA 1.6.2? I just tried to reproduce this under macOS Sierra, v10.12.1 but I do not get this error. Thanks!

**Comment by mad4linux** [comment]
Bug is no longer present in Version 1.6.2. Can be closed
