### ISSUE TITLE
Hungarian translation missing from menu

### ISSUE THREAD

**Issue by arturszilagyi** [GreenDelta/olca-app#103]
Although Hungarian translation file is available, it is not listed in olca-app/src/org/openlca/app/preferences/Language.java

**Comment by msrocka** [comment]
thanks, I merged your pull request and it should work:

![image](https://user-images.githubusercontent.com/3520062/74429403-2c460c00-4e5b-11ea-9bdd-8fdf9368bdc8.png)

However, we should update the translations at some point...
