### ISSUE TITLE
Allow to select product systems as provider of a flow in the "Inputs/Outputs" tab of a process

### ISSUE THREAD

**Issue by ghost** [GreenDelta/olca-app#109]
Hello, I have a feature suggestion. 

If I am not mistaken, currently product systems can only be set as the provider of a flow in another product system's model graph. It would be very nice if a product system could already be selected as the provider of a flow in the *Inputs/Outputs* tab of a process.

Just a thought :) Keep up the great work!

**Comment by msrocka** [comment]
It is a good idea but we will not go for it for now. Linking product systems to processes breaks somehow the hierarchy and has implications on data export, usage search etc. In openLCA 2 even results can be linked as providers to product inputs (or waste outputs) in product system; and they can link to a product system again. That said, we may re-open this issue later.
