### ISSUE TITLE
Group for global parameters

### ISSUE THREAD

**Issue by n1c0l492** [GreenDelta/olca-app#116]
Would be useful if a group of global parameters is implemented. The scope is to separate global parameters into groups to make the selection in processes tabs easier since only a group of parameters could be selected to be shown.

**Comment by msrocka** [comment]
@n1c0l492 do you mean to group the parameters in the pop-up of the formula editor (see below) or where should the groups be applied? also, we have already categories for global parameters so maybe these could be used for the grouping.

![image](https://user-images.githubusercontent.com/3520062/99389333-2cd26e00-28d7-11eb-9e01-9a2447db0bc0.png)

**Comment by msrocka** [comment]
Closing this issue because it is a bit unclear what is meant and how this could be fixed. Feel free to reopen it if more details are available.
