### ISSUE TITLE
Script API - Product System - Processes

### ISSUE THREAD

**Issue by nick-transition** [GreenDelta/olca-app#12]
Removing processes from a product system is not functioning correctly. 

One would expect the at least one if not both of the statements below to remove all processes from a product system.
```python
olca.getSystem("rice").getProcesses().clear()
olca.getSystem("rice").getprocesses().removeAll(olca.getSystem("rice").getProcesses())
log.info(str(olca.getSystem("rice").getProcesses().isEmpty()))
```
Currently the output is false (processes are present).

System: Windows 10 64-bit
OLCA version: 1.5.0 beta1

**Comment by msrocka** [comment]
You have to save the changes to the database via `olca.updateSystem`. This should work: 

```python
log.info(str(olca.getSystem("rice").getProcesses().isEmpty())) # -> False

system = olca.getSystem("rice")
system.getProcesses().clear()

# save changes to the database
system = olca.updateSystem(system)
# ...

log.info(str(olca.getSystem("rice").getProcesses().isEmpty())) # -> True
````
