### ISSUE TITLE
Unable to select LCIA Method in detached project tab

### ISSUE THREAD

**Issue by ghost** [GreenDelta/olca-app#122]
When I detach a tab in which I've opened a project, I cannot select an LCIA Method. I'm using openLCA 1.10 on Windows 10.

**Comment by msrocka** [comment]
This is a problem of the [Nebula table-combo widget](https://www.eclipse.org/nebula/widgets/tablecombo/tablecombo.php) that we cannot fix in openLCA. The table is drawn behind the detached window. You can see this when you make that window small and move it around:

![image](https://user-images.githubusercontent.com/3520062/181754093-94beb98b-6c4e-49cb-ba3c-7c0da85740c9.png)
