### ISSUE TITLE
Missing Jar Files 

### ISSUE THREAD

**Issue by NageshBabuS** [GreenDelta/olca-app#129]
olca-cloud-2.0.0.jar
olca-core-2.0.0.jar
olca-ecospold-1-2.0.0.jar
olca-ecospold-2-2.0.0.jar
olca-formula-2.0.0.jar
olca-ilcd-2.0.0.jar
olca-io-2.0.0.jar
olca-ipc-2.0.0.jar
olca-proto-2.0.0.jar
olca-simapro-csv-2.0.0.jar

we don't have above jar files and we don't have "libs" folder also this app
please find attached screens for more info. 
![MissingJarfiles](https://user-images.githubusercontent.com/78583769/106997967-c9efc500-67a9-11eb-9c54-4bad020c212f.PNG)

**Comment by msrocka** [comment]
You need to follow the instructions in the README to get these dependencies:

1. Install the `olca-modules`: https://github.com/GreenDelta/olca-app#install-the-openlca-core-modules
2. Run `mvn package` in the `olca-app` project: https://github.com/GreenDelta/olca-app#copy-the-maven-modules
