### ISSUE TITLE
Calculation fails for product systems without elementary flows (intervention matrix)

### ISSUE THREAD

**Issue by SebaJeku** [GreenDelta/olca-app#13]
When I want to evaluate my Product System "HS10 Fair" (just a small one), I always get an "Unexpected Error during Evaluation". It worked once but now it refused. I did a small change in between, don't know what exacty, but to me the model seems to be o.k.

Can you find out the reason?

See attached: Log Messages, Configuration, and Project (.zolca) in a ZIP

Environment: 
* Windows 10 64-bit
* openLCA 1.5.0

[Seba.zip](https://github.com/GreenDelta/olca-app/files/767368/Seba.zip)

**Comment by msrocka** [comment]
Thank you for reporting this issue and the example, log-file etc. (very helpful). The reason for this is that there is no elementary flow in the product system which throws an internal error in the calculation (I updated the title of this issue accordingly).
 
A quick fix that you can continue your work: If you add an elementary flow to a process (e.g. CO2 to the `Erdöl` process) the calculation should work.

Thanks, Michael

**Comment by SebaJeku** [comment]
Ok, thanks Michael, that was kind of stupid... Thanks for analysing. Of course, a more elaborate error message could help :-)

**Comment by msrocka** [comment]
@SebaJeku I keep this issue open because it is really an internal error. I think there are valid cases where you could run a calculation without elementary flows (e.g. life cycle costing calculations, testing during the development of a product system, etc.)

**Comment by msrocka** [comment]
This calculation does not crash anymore in openLCA 2
