### ISSUE TITLE
Request OpenLCA Version 1.10.1 Installation File 

### ISSUE THREAD

**Issue by Simonsteffl** [GreenDelta/olca-app#130]
Hello GitHub community,
i am looking for the older OpenLCA version 1.10.1 installation file.
Maybe some of you can send me a download link?
All the best
Cheers Simon

**Comment by msrocka** [comment]
It seems that it is still on the openLCA server here: https://www.openlca.org/wp-content/uploads/2019/11/

Note that the openLCA forum is better for these questions (https://ask.openlca.org/) as we use Github issues more to track bugs and the development of new features. Thanks.
