### ISSUE TITLE
oLCA desktop Repository>#Configure repositories path list not generating

### ISSUE THREAD

**Issue by uslci-admin** [GreenDelta/olca-app#133]
In attempting to commit a local oLCA database to an existing repo on the LCA Commons Collaboration Server, via the 'Add a new repository' screen, I twice received the error "unable to find valid certification path to requested target". On the third (and several subsequent) attempts to connect, fetch changes, and commit my local database to the server, the repository configuration seems to get hung before this step and can't generate the repositories paths list (i.e., the pull-down menu is blank). I do have 'Enable Collaboration' checked in my oLCA desktop settings and have double-checked my server URL and sign-in credentials. I am using openLCA v1.10.3 via a Windows 10 Pro operating system desktop. I have also tried on my laptop (same oLCA version & OS) and my remote Collaboration Server admin/colleague has duplicated the blank repositories pull-down hang-up at their desktop with their admin credentials.

**Comment by SebastianGreve-GreenDelta** [comment]
The connection to the repository has been replaced by a different workflow in the 2.0 version of openLCA
