### ISSUE TITLE
Monte Carlo Simulation Version 2.0.0 alpha2

### ISSUE THREAD

**Issue by gthoma** [GreenDelta/olca-app#136]
MCS in Version 2.0 alpha fails. Using the GUI, if I set up an MCS for a product system, it will create the start screen without issue. But when pressing the start button to initiate the simulation, it runs immediately and stops without any simulations.

**Comment by msrocka** [comment]
Many thanks for reporting this issue. Is this still an issue in the current [beta version](https://share.greendelta.com/index.php/s/76uAFtMKDIWGoXC)?

**Comment by msrocka** [comment]
openLCA 2 is released now, so closing this issue. If there are still issues with the MC simulation, please re-open it or file a new issue. Thanks!
