### ISSUE TITLE
Running the IPC server headless

### ISSUE THREAD

**Issue by zond** [GreenDelta/olca-app#143]
I would like to start the IPC server running a given database without opening the UI.

Is this possible today?

If not, I might want to contribute code for that purpose.

If you think this is a good idea, I'd greatly appreciate some pointers about where the app actually starts (I'm unused to your build system, and haven't found a main function entry point?) and any advice about how to get the application running without a user interface.

**Comment by msrocka** [comment]
Yes, it is possible to run the IPC server in headless mode. This is the Maven module of the IPC server:
https://github.com/GreenDelta/olca-modules/tree/master/olca-ipc

There are some details in the readme and there is a Maven profile for building the stand-alone server. The entry point with the main-function of the server is here: https://github.com/GreenDelta/olca-modules/blob/master/olca-ipc/src/main/java/org/openlca/ipc/Main.java#L137

**Comment by zond** [comment]
Excellent, thank you!

I have already run into a few problems, but will create a new issue in the olca-modules repo for that :D
