### ISSUE TITLE
v1.11 eclipse error

### ISSUE THREAD

**Issue by tcollard** [GreenDelta/olca-app#154]
Hi,

I try to launch the v1.11 in debug mode with Eclipse but I've some error.

The first error is about `org.eclipse.swt.graphics.RGB`
```
The type org.eclipse.swt.graphics.RGB cannot be resolved. It is indirectly referenced from required .class files	ColorCalculator.java	/olca-app/src/org/openlca/app	line 1	Java Problem
```
The other one, it's when I launch it. I can see in the log it's about `org.eclipse.swt.SWTError`

```
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWTError cannot be found by org.eclipse.ui.workbench_3.119.0.v20200521-1247
```

I've try to fixed it, but I'm stuck. If someone have any idea.
Thanks

**Comment by msrocka** [comment]
Did you load the target platform as described here: https://github.com/GreenDelta/olca-app#loading-the-target-platform ? Maybe you need to reload it.

**Comment by tcollard** [comment]
Thanks a lot !!! It's working perfectly now  🥳
The java version on eclipse wasn't the good one.

Thank you for your time
