### ISSUE TITLE
Adding a repository using a 2FA enabled account

### ISSUE THREAD

**Issue by cdeces** [GreenDelta/olca-app#166]
When adding a new repository using a 2FA enabled account, the window used to enter the token is covered by the progress information window, see screenshot below.
Observed with OpenLCA 1.11.0

![openlca 2fa issue](https://user-images.githubusercontent.com/102837949/161356497-a7dceb13-84b8-4fd1-99a1-a9883fd5fecf.PNG)

**Comment by SebastianGreve-GreenDelta** [comment]
In openLCA 2.0 the connection dialog was replaced, so this should not be a problem anymore
