### ISSUE TITLE
2.0.0.alpha4 - Global parameter sorting

### ISSUE THREAD

**Issue by jensfpeters** [GreenDelta/olca-app#181]
In the "Indicators and Parameters" list, Global parameters are not sorted alphabetically but according to the order of introduction, making it difficult to find a given parameter if you have many.

**Comment by msrocka** [comment]
Ah, correct, they are sorted but in case-sensitive order, right?

![image](https://user-images.githubusercontent.com/3520062/166454756-49f3bcc4-022c-4642-aa17-83f70c0e29d5.png)

**Comment by msrocka** [comment]
this should be fixed in the next release:

![image](https://user-images.githubusercontent.com/3520062/166457609-924fe366-6f9c-4b5b-96e5-8959a7a94a3a.png)

**Comment by msrocka** [comment]
This should be fixed in the current [beta version](https://share.greendelta.com/index.php/s/76uAFtMKDIWGoXC).
