### ISSUE TITLE
1.4.1-beta4-No option to save product system after building supply chain

### ISSUE THREAD

**Issue by WesIngwersen** [GreenDelta/olca-app#2]
I made a product system without connecting processes, then build a supply chain using the Model graph editor, but do not have the option to save the product system.

**Comment by msrocka** [comment]
Hi Wes,

This should be also fixed in the current [release candidate for 1.4.1](https://sourceforge.net/projects/openlca/files/openlca_framework/1.4.1_rc/).

Thank you,
Michael
