### ISSUE TITLE
unable to download OpenLCA RCP Platform

### ISSUE THREAD

**Issue by priyaII** [GreenDelta/olca-app#22]
![image](https://cloud.githubusercontent.com/assets/20396800/26640228/c822f4f2-4644-11e7-9018-8cd29f0e92ec.png)

I was following your instructions regarding "Within Eclipse right-click on the olca-app-runtime/build.xml file and select Run as.../Ant build. This will download the RCP platform on which openLCA is built"

1) Its causing an error
2) There are 2 options under Run As >> Ant Build >> Ant Build..
  which is suitable?

**Comment by msrocka** [comment]
Thank you for posting this issue. Could you also copy the error message from the console into the issue description? Thanks.

Regarding the Ant options: `Ant build` should work (normally).

**Comment by priyaII** [comment]
on the console: 

Buildfile: C:\Users\Administrator\Documents\GitHub\olca\olca-app\olca-app-runtime\build.xml
main:
clean:
download:

BUILD FAILED
C:\Users\Administrator\Documents\GitHub\olca\olca-app\olca-app-runtime\build.xml:15: The following error occurred while executing this line:
C:\Users\Administrator\Documents\GitHub\olca\olca-app\olca-app-runtime\build.xml:31: get doesn't support the "skipexisting" attribute

Total time: 892 milliseconds
______________________________________________________________

**Comment by priyaII** [comment]
I am unfamiliar with Java.
Can this way be used? 
I found a file shared on OpenLCA site 
![image](https://cloud.githubusercontent.com/assets/20396800/26675160/7411ed40-46e0-11e7-934d-4db8b81bb471.png)

File - http://www.openlca.org/wp-content/uploads/2015/11/How-to-import-the-openLCA-source-code-into-Eclipse.pdf
______________________________

Could you recommend any concepts/online courses I could do in order to contribute to OpenLCA? Currently, I am trying to integrate a  visualisation into the SunBurst Window.

**Comment by msrocka** [comment]
Regarding the error `get doesn't support the "skipexisting" attribute`:

The `skipexisting` attribute was added in [Ant 1.8.0 ](https://ant.apache.org/manual/Tasks/get.html). Eclipse Neon has Ant 1.9.6 included. This is probably related to the document from the openLCA web site which states that you should use Eclipse Galileo: No, this document is not valid anymore. The build descriptions in the [README file](https://github.com/GreenDelta/olca-app/blob/master/README.md) contain the current steps to build openLCA from source. Contributions to this file to make these build steps clearer are very welcome.
