### ISSUE TITLE
imported jsonld files that contain "tags" properties and are imported lose the tags when later exported

### ISSUE THREAD

**Issue by xtitter** [GreenDelta/olca-app#221]
The "tags" property is specified in the [CategorizedEntity](http://greendelta.github.io/olca-schema/CategorizedEntity.html) in the ocla schema.  While it appears that the OpenLca application has no interface to show tags, it won't even persist them across and import and export cycle.

**Comment by msrocka** [comment]
Tags were added in openLCA 1.11. They can be added and removed in the respective data set editors:

![image](https://user-images.githubusercontent.com/3520062/181215615-edfa217f-72c3-4256-9956-e3d9742397c7.png)

In openLCA 2, there is even an experimantal result view to group result contributions by tags:

![image](https://user-images.githubusercontent.com/3520062/181216787-664b4863-7aa5-49b8-969f-3c4675a9e54a.png)

**Comment by xtitter** [comment]
That is great. Thanks.

My planned use of the tags will be for tools external to the openLca application.  To keep things isolated, I expect I'll use key:value pairs for each tag, with some sort of special character delimiter and a specific key that the external tool looks for.  Unfortunately, this is going to be somewhat clunky for the result grouping view that you've shared above.

I wonder if this is reasonable functionality to add to the ocla-schema and/or the openLca application?  It would allow for tagging that supports orthogonal purposes: i.e., the results view could group based on tag values with a specific key, etc.

**Comment by msrocka** [comment]
Yes, this would be a very useful addition and we indeed plan to support such key-value pairs in one of the next versions. We wouldn't use the `tags` field for this but add some other field; not sure about the name yet, maybe just `properties`. Also, we plan to support not only string values but also structured types (basically JSON), e.g. in olca-schema it could look like this:

```js
{
  "@type": "Process",
  "@id": "123...",
  // ...
  "properties": {
    "the": {
      "result": "of it",
      "is": [42]
    }
  }
}
```

This should be editable in the user interface of openLCA then; maybe something like the `about:config` page in Firefox as an additional tab in the data set editors which could be enabled via the application settings:

![image](https://user-images.githubusercontent.com/3520062/181459389-50451e8f-ac4f-41c2-bfd8-8df6bdc5350c.png)

**Comment by msrocka** [comment]
Closing this because there is a separate issue now: https://github.com/GreenDelta/olca-app/issues/232
