### ISSUE TITLE
Support quantity groups, units and conversions with a unit ontology database.

### ISSUE THREAD

**Issue by francoislerall** [GreenDelta/olca-app#230]
For example, these two organisations provide various quantity and unit standards:
 - https://qudt.org/
 - http://www.ontology-of-units-of-measure.org/

Two possibilities:
 - create an action in openLCA to retrieve data and update units and conversion,
 - automatically update units and conversion when creating a new release.

**Comment by msrocka** [comment]
Closing this issue here because we can use the [data repository](https://github.com/GreenDelta/data) for such issues/fixes. When creating the reference database templates, it fetches the data from this repository now.
