### ISSUE TITLE
OpenLCA is still "broken" after following the solution reddit thread provided online by OpenLCA

### ISSUE THREAD

**Issue by stanalexander101** [GreenDelta/olca-app#263]
After reading through and following the instructions found in the reddit thread provided by OpenLCA, I still have not been able to get the app to work. I have tried moving it to different folders, downloading it off multiple different browsers (e.g., chrome, safari, etc...), and have tried copying the command into the terminal app. However, it still says "no file found" when carrying out the command. I have a 2017 Macbook Pro with intel software.

Is there a new command that needs to be used? Could my anti-virus software be a reason why? 

Thank you so much to those who can help!

Thread provided by OpenLCA: [https://github.com/GreenDelta/olca-app/issues/152)](https://github.com/GreenDelta/olca-app/issues/152)

**Comment by msrocka** [comment]
yes, the issue is not yet solved, there are different workarounds described in the #152 thread. I think we shouldn't open a second issue for this...
