### ISSUE TITLE
UUIDs are sometimes cropped

### ISSUE THREAD

**Issue by NansD** [GreenDelta/olca-app#272]
![image](https://user-images.githubusercontent.com/18481465/203993609-215ed53e-364f-43a4-8cd1-1c5ec364f043.png)

In OLCA 2.0, UUIDs are sometimes cropped, making it impossible to copy it.
It would be great if we could copy them easily !

**Comment by francoislerall** [comment]
Hi @NansD,
Thanks for raising this up. It should be fixed by https://github.com/GreenDelta/olca-app/commit/601c4f1bedd6bccbe9ed7dfe2e2b8c38ef99898e.
