### ISSUE TITLE
jblas library not available on all linux distributions

### ISSUE THREAD

**Issue by bkuczenski** [GreenDelta/olca-app#28]
Please include the compiled jblas-1.2.4.jar in the binary distribution

**Comment by bkuczenski** [comment]
On arch, `libgfortran.so.3` is outmoded (my distribution has `libgfortran.so.4` installed natively). However, it is available in the package `gcc6-libs`. After installing this package and performing the following as root:
    # cd /usr/lib
    # ln -s gcc/[arch]/6.x.x/libgfortran.so.3
I was able to start the program without the jblas notification.
But if jblas is all you need, why not include it with the binary?

**Comment by msrocka** [comment]
The `jblas` notification is outdated. We do not use jblas anymore but directly include [OpenBLAS binaries](https://github.com/xianyi/OpenBLAS). On Windows and macOS we link gfortran statically.

However, I think you also need to install [libgfortran3 with jblas](https://github.com/mikiobraun/jblas/wiki/Missing-Libraries) … (at least in older versions). When I compile the Linux binaries next time, I will try to link everything statically (but there were some problems; I do not remember).

**Comment by msrocka** [comment]
see https://github.com/GreenDelta/olca-app/issues/85#issuecomment-540043587
