### ISSUE TITLE
Change default allocation method to "As defined by process"

### ISSUE THREAD

**Issue by bl-young** [GreenDelta/olca-app#299]
Version 1.10

I would suggest setting the default option for allocation for product systems to "As defined by process" instead of "None".

The importance of this selection can be missed by some users which can lead to unintended results when there are multi-product processes in the supply chain. (Specifically we find this in the US LCI petroleum process)

![image](https://user-images.githubusercontent.com/44471635/217834140-97e250ba-3efb-4342-b9a6-f26adac9e143.png)

I have not checked if this is still the case in v2.0 alpha

**Comment by msrocka** [comment]
@bl-young many thanks for this suggestion. This is the default option in openLCA 2 now (and the calculation preferences should be handled a bit smarter in general now). Closing this issue as openLCA 2 is released now.
