### ISSUE TITLE
1.4.1 beta 6 - Import of ILCD does not preserve flow location

### ISSUE THREAD

**Issue by WesIngwersen** [GreenDelta/olca-app#3]
If processes are exported into ILCD, import of an ILCD file into a new database causes flow locations to be lost.

**Comment by msrocka** [comment]
Hi Wes,

Thank you for posting this issue. This should be fixed now in the [release candidate for version 1.4.1](https://sourceforge.net/projects/openlca/files/openlca_framework/1.4.1_rc/).

Best regards,
Michael
