### ISSUE TITLE
Duplicate internalIDs in the same process

### ISSUE THREAD

**Issue by pweiler2** [GreenDelta/olca-app#306]
Version 1.11 and Version 1.10.3

We have found several processes within the USLCI database on OpenLCA that have duplicate internalIDs. These internalIDs are intended to be unique within the same process so we are unsure of what's causing these duplicates and how to resolve the problem. The screenshot below contains examples of duplicate internalIDs within the same process. 

![image](https://user-images.githubusercontent.com/101887770/223132519-156f2b29-4b8b-4321-99bc-e40b91f98daa.png)

**Comment by msrocka** [comment]
The ID of a process is unique but the internal ID (of an exchange) is only unique within a process (internally). It identifies the exchanges within that process.

**Comment by pweiler2** [comment]
Thanks for the quick response! Since the internal ID identifies exchanges within a process and is thus unique within a process, I'm unclear as to why we're finding duplicate internal IDs within the same process. For example, "Portland Cement, at plant" has multiple exchanges that have the same internal ID, see screenshot below. Thanks for the help! -Paige
![image](https://user-images.githubusercontent.com/101887770/223154312-586796de-4074-4b01-8743-cc1d58b34e76.png)

**Comment by msrocka** [comment]
Correct, these are errors in the current US-LCI database. Also, the `last_internal_id` is a counter and must be always greater than or equal to the max. internal exchange ID of the process. It seems that this is also not always true:

```sql
select p.ref_id, p.last_internal_id, max(e.internal_id) 
  from tbl_processes p inner join tbl_exchanges e on e.f_owner = p.id 
  group by p.ref_id, p.last_internal_id 
  having p.last_internal_id < max(e.internal_id)
```
Maybe [US-LCI repository](https://github.com/uslci-admin/uslci-content) is the right place for this issue?

**Comment by pweiler2** [comment]
I'm part of the team that manages USLCI. This question originally came into us so we looked into it but we thought that it was an error caused by OpenLCA rather than the database itself. Do you have any suggestions on how to go about fixing it or what caused the internal ID errors in the first place? Thanks!

**Comment by msrocka** [comment]
Depends maybe how the data is managed but this script should fix the JSON-LD package (tested with Python 3.11; the file name of the JSON-LD package is passed as argument into the script):

```py
import datetime
import json
import sys
import zipfile as zf

from pathlib import Path
from typing import Any


def main():
    if len(sys.argv) < 2:
        print("no JSON-LD package provided")
        return
    ipack = Path(sys.argv[1])
    if not ipack.exists():
        print(f"not a file: {ipack}")
        return
    opack = Path(sys.argv[1] + "_fixed.zip")
    if opack.exists():
        print(f"{opack} already exists")
        return
    with zf.ZipFile(ipack, mode="r") as source:
        with zf.ZipFile(opack, mode="w", compression=zf.ZIP_DEFLATED) as target:
            pipe(source, target)


def pipe(source: zf.ZipFile, target: zf.ZipFile):
    for e in source.filelist:
        if e.is_dir():
            continue
        data = source.read(e.filename)
        if "processes" in e.filename:
            d = json.loads(data)
            data = fix_process(d)
        target.writestr(e.filename, data)


def fix_process(p: dict[str, Any]) -> str:
    err = f"error in process {p.get('@id', '???')}:"
    last_id = p.get("lastInternalId", 0)
    needs_update: bool = last_id == 0
    exchanges: list[dict] = p.get("exchanges", [])
    used_ids: set[int] = set()

    # check that the last internal ID is valid
    for e in exchanges:
        eid = e.get("internalId", 0)
        if eid > last_id:
            print(f"{err} last internal ID smaller than exchange ID {eid}")
            needs_update = True
            last_id = eid

    # fix duplicates and missing internal IDs
    for e in exchanges:
        eid = e.get("internalId", 0)
        if eid == 0:
            print(f"${err} exchange without internal ID")
            needs_update = True
            last_id += 1
            e["internalId"] = last_id
            continue
        if eid in used_ids:
            print(f"${err} duplicate internal ID {eid}")
            needs_update = True
            last_id += 1
            e["internalId"] = last_id
            continue
        used_ids.add(eid)

    if needs_update:
        p["lastInternalId"] = last_id
        p["lastChange"] = datetime.datetime.utcnow().isoformat() + 'Z'
        # maybe also update the version

    return json.dumps(p)


if __name__ == "__main__":
    main()
```

**Comment by pweiler2** [comment]
That worked - thanks!
