### ISSUE TITLE
openLCA 1.7.2 failed to delete category

### ISSUE THREAD

**Issue by ezrakahn** [GreenDelta/olca-app#33]
Error from log.html:

737050 | JavaFX Application Thread | ERROR | org.openlca.app.navigation.actions.DeleteModelAction | failed to delete category Category {modelType=PROCESS, refId=1b044fcc-06a7-32e6-8072-abaa636328ef, name=North Carolina}
-- | -- | -- | -- | --
org.mapdb.DBException$EngineGetVoid: Recid passed to Engine.get() does not exist. Possible data corruption!     	at org.mapdb.StoreDirect.indexValGet(StoreDirect.java:1565)     	at org.mapdb.StoreWAL.indexValGet(StoreWAL.java:433)     	at org.mapdb.StoreWAL.get2(StoreWAL.java:643)     	at org.mapdb.Store.get(Store.java:253)     	at org.mapdb.Engine$CloseOnJVMShutdown.get(Engine.java:453)     	at org.mapdb.DB$4.run(DB.java:205)     	at org.mapdb.DB$4.run(DB.java:199)     	at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:460)     	at org.mapdb.SerializerBase.serialize(SerializerBase.java:1000)     	at org.mapdb.SerializerBase.serialize(SerializerBase.java:946)     	at org.mapdb.HTreeMap$1.serialize(HTreeMap.java:143)     	at org.mapdb.HTreeMap$1.serialize(HTreeMap.java:127)     	at org.mapdb.Store.serialize(Store.java:304)     	at org.mapdb.StoreCached.flushWriteCacheSegment(StoreCached.java:389)     	at org.mapdb.StoreWAL.commitFullWALReplay(StoreWAL.java:838)     	at org.mapdb.StoreWAL.commit(StoreWAL.java:726)     	at org.mapdb.Engine$CloseOnJVMShutdown.commit(Engine.java:487)     	at org.mapdb.DB.commit(DB.java:2621)     	at org.openlca.app.cloud.index.DiffIndex.commit(DiffIndex.java:182)     	at org.openlca.app.db.IndexUpdater.delete(IndexUpdater.java:82)     	at org.openlca.app.db.DatabaseListener.modelDeleted(DatabaseListener.java:52)     	at org.openlca.core.database.Notifiable.notifyDelete(Notifiable.java:37)     	at org.openlca.core.database.RootEntityDao.delete(RootEntityDao.java:48)     	at org.openlca.app.navigation.actions.DeleteModelAction.delete(DeleteModelAction.java:214)     	at org.openlca.app.navigation.actions.DeleteModelAction.delete(DeleteModelAction.java:187)     	at org.openlca.app.navigation.actions.DeleteModelAction.run(DeleteModelAction.java:143)     	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)     	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)     	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)     	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)     	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)     	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)     	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)     	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)     	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)     	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)     	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)     	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)     	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)     	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)     	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)     	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)     	at org.openlca.app.rcp.RcpApplication.start(RcpApplication.java:16)     	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)     	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)     	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)     	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)     	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     	at java.lang.reflect.Method.invoke(Method.java:498)     	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)     	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)     	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by msrocka** [comment]
@sebastian-greve this is related to the repository/Collaboration server integration (the MapDB index), right?
