### ISSUE TITLE
OLCA 2.0 crashes running Monte Carlo

### ISSUE THREAD

**Issue by gthoma** [GreenDelta/olca-app#337]
I am using the 2.0 release and when I run MCS the program crashes after a few 10's of runs. I was able to get 50, one time. When I set the number to 100, it consistently crashes (tried multiple times). I have attached the error log from the last crash.
[hs_err_pid11328.log](https://github.com/GreenDelta/olca-app/files/11575587/hs_err_pid11328.log)
Here is my *ini file:
-nl
en
-olcaDataDir
D:\olca2B3Dbase
-data
-theme
default
@noDefault
-vmargs
-Xmx56000M
-Dpython.console.encoding=UTF-8
-Dorg.eclipse.swt.browser.DefaultType=edge
--add-modules=ALL-SYSTEM

**Comment by gthoma** [comment]
Update: I deleted and re-downloaded the installation zip file and changed the database directory. The program crashed after ~25 MCS runs.
here is the error log 
[hs_err_pid47180.log](https://github.com/GreenDelta/olca-app/files/11595361/hs_err_pid47180.log).

**Comment by msrocka** [comment]
Many thanks for reporting this issue and attaching the log file. The error happens in the native code of a calculation library and this is why the whole application crashes. Probably the factorization of the matrix fails in a simulation run and this case is not correctly handled currently.

From the log file it is visible that this happens with the calculation libraries for dense matrices. What could help is to install the libraries for sparse matrices (following the link on the start page or under the application preferences) as the calculation then is more stable if the system is sparse (e.g. when using ecoinvent).

**Comment by francoislerall** [comment]
I am closing the issue as there was no feedback.
Feel free to comment and reopen if necessary.
