### ISSUE TITLE
Collaboration Server Settings Broke in 2.0.0

### ISSUE THREAD

**Issue by intrepidvaillant** [GreenDelta/olca-app#338]
In 2.0.0 on Linux and Windows the collaboration server setting have just disappear making it impossible to add a remote server.

![image](https://github.com/GreenDelta/olca-app/assets/65712491/b3097cdf-f9fa-4953-9c6c-662a8ed44622)

**Comment by intrepidvaillant** [comment]
I have retry on the last snapshot, it doesn't work either.
![image](https://github.com/GreenDelta/olca-app/assets/65712491/17fbfabd-fb1d-453d-9d8a-d5c6271a4ead)

**Comment by Leeeks** [comment]
You connect your Collaboration Server by right-clicking on your Database. There is a new context menu entry.
![image](https://github.com/GreenDelta/olca-app/assets/47191992/a68fe823-6d55-44f4-8ca9-b2a125bcad9d)

**Comment by SebastianGreve-GreenDelta** [comment]
Connections are not managed anymore in the preferences, also the "Repository" menu is now active by default and does not need to be enabled anymore
