### ISSUE TITLE
Some links are not shown in the Sankey diagram

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/olca-app#339]
Here is an example to reproduce this; it can be executed in the openLCA Python editor e.g. with an empty database activated:

```python

units = UnitGroup.of("Mass units", "kg")
mass = FlowProperty.of("Mass", units)
e = Flow.elementary("e", mass)
a = Flow.product("a", mass)
b = Flow.product("b", mass)
c = Flow.product("c", mass)

A = Process.of("A", a)
A.input(b, 1)
A.input(c, 1)
A.output(e, 1)

B = Process.of("B", b)
B.output(e, 10)

C = Process.of("C", c)
C.input(b, 1)
C.output(e, 1)

db.insert(units, mass, e, a, b, c, A, B, C)

abc = ProductSystem.of("ABC", A)
abc.link(B, A)
abc.link(C, A)
abc.link(B, C)

prev = C
for i in range(1, 21):
  di = Flow.product("d%d" % i, mass)
  Di = Process.of("D%d" % i, di)
  Di.output(e, 1)
  db.insert(di, Di)
  prev.input(di, 1)
  prev = db.update(prev)
  abc.link(Di, prev)
  prev = Di

db.insert(abc)

App.runInUI("refresh ...", lambda: Navigator.refresh())
App.open(abc)

```

Calculating the system will generate an upstream tree for flow `e` like this:

![image](https://github.com/GreenDelta/olca-app/assets/3520062/0ec89d86-17be-487e-93d0-332ff5e1e946)

Process `B` is an input into `A` and `C`. However, this link is not always shown in the Sankey diagram:

![image](https://github.com/GreenDelta/olca-app/assets/3520062/2898c974-b9ca-4183-a904-7c8193397eff)

When limiting the number of processes to `3` it is visible:

![image](https://github.com/GreenDelta/olca-app/assets/3520062/4c3752ba-d936-4a4a-9f68-099dd6635648)

It seems that this is only a display problem. The link should be available in the model, which can be checked with this script:

```python
abc = db.get(ProductSystem, "73e8e99a-657d-4845-8b99-5d692d8d35f9")
setup = CalculationSetup.of(abc)
result = SystemCalculator(db).calculate(setup)
sankey = Sankey.of(result.enviIndex().at(0), result.provider())\
  .withMaximumNodeCount(10)\
  .build()\
  .toDot()
print(sankey)
```

This prints the graph in Dot format which can be rendered, e.g. with webgraphviz.com:

![image](https://github.com/GreenDelta/olca-app/assets/3520062/8a5fcf19-f272-47de-9ab4-00723aad088c)

**Comment by francoislerall** [comment]
Output B: 10
![image](https://github.com/GreenDelta/olca-app/assets/43290668/dde7f2d2-a405-4144-803e-a7a56ed9b794)
Output B: 1
![image](https://github.com/GreenDelta/olca-app/assets/43290668/0ef1bcdf-3e50-4617-b9f9-a83a3b42ee17)
