### ISSUE TITLE
Conversion function in the flow mapping tool switches units

### ISSUE THREAD

**Issue by pweilerERG** [GreenDelta/olca-app#395]
When entering individual flow mapping lines there is a conversion factor field (e.g., .001 m3/kg). After selecting "OK" the units switch so it appears as .001kg/m3 and this is what is applied on the database.
![image](https://github.com/GreenDelta/olca-app/assets/101887770/ccf46f05-314a-44a1-baa3-abd6772ec2d6)

![image](https://github.com/GreenDelta/olca-app/assets/101887770/a2565a8d-2ae2-48bd-81de-799f9cdd7715)

**Comment by msrocka** [comment]
Thank you. This should be fixed in the next release (2.2.0). For this example, the factor should be `1000 kg/m3` in both places (`x m3 * 1000 kg/m3 = y kg`).
