### ISSUE TITLE
Bulk/Replace Tool limitations

### ISSUE THREAD

**Issue by uslci-admin** [GreenDelta/olca-app#43]
You must widen the tool window to fully read flow names and even then, not all seem to be listed (e.g., using standard reference data, there are 5 dimethyl sulfate flows but only 2 are available as options for replacing and it is unclear from which subcompartments these flows originate—even with the window widened as much as possible)

**Comment by msrocka** [comment]
There is now a [flow mapping tool](https://www.openlca.org/wp-content/uploads/2020/06/General-openLCA-Mapping-Instructions_05182020.pdf) integrated in openLCA.  Still experimental but already tested in some projects. It can also replace flows in a database and has much more features than the bulk-replace-tool. The idea is also that this will fully replace the bulk-replace-tool in some future version.
