### ISSUE TITLE
Diff Window as a change log

### ISSUE THREAD

**Issue by uslci-admin** [GreenDelta/olca-app#44]
It would be nice to have the ability to copy, save, and/or print the Diff Window when fetching changes (as a change log).

**Comment by uslci-admin** [comment]
Just reiterating that the US Federal LCA Commons would love to use the Diff Window tool as an automated change log. Would make publishing change logs for transparency much more consistent between agencies.

**Comment by SebastianGreve-GreenDelta** [comment]
Closing because change log feature was implemented in Collaboration Server
