### ISSUE TITLE
Collaboration server can't delete old processes

### ISSUE THREAD

**Issue by uslci-admin** [GreenDelta/olca-app#45]
As a collaboration server repository owner/editor, I am able to commit process and flow deletions. However, when logged in as a public viewer to the same repository, the old processes and flows are visible but have no content (i.e., fields are blank).

**Comment by sebastian-greve** [comment]
Could you please specify if you are in the "public search" or "anonymous" user? There is no "public viewer" role or anything as a logged in user. 

Also, is it in the browsing view of a repository (when navigating to a repository and then clicking data sets to navigate through the categories) or in the search view. 

In general this is somehow expected, you can find deleted data sets and from there navigate to previous versions, but only the logged in user should be able to do that. It should show a small badge "Deleted" on the top right of the data set header

**Comment by SebastianGreve-GreenDelta** [comment]
The search feature was redesigned in the current version, so this should be obsolete
