### ISSUE TITLE
List flows that were not considered by the LCIA method during the analysis calculation

### ISSUE THREAD

**Issue by DonMeadows** [GreenDelta/olca-app#53]
It would be nice if openLCA, following the analysis calculation, would list all flows that are linked to the product system under consideration which were not considered by the LCIA method with which the calculation was performed.

**Comment by msrocka** [comment]
Additionally,:
* [ ] Show the LCIA results of a single process (e.g. in the process editor),
* [x] Show the characterization factors of a single flow (in the flow editor; already done)
