### ISSUE TITLE
Improvements to drag and drop functionality

### ISSUE THREAD

**Issue by DonMeadows** [GreenDelta/olca-app#56]
The drag and drop functionality in openLCA is very useful but does not work for all database items/situations. Support for the following situations would be nice

- Support drag and drop during split view (this would allow to easily drag and drop flows from the Inputs/Outputs list of a process into the Inputs/Outputs list of another process
- Support drag and drop of product systems into the "Compared product systems" list of a project.

**Comment by msrocka** [comment]
regarding the first point: there is the copy and paste function for inputs and outputs that also works for copying them between processes.

regarding the second point: I will add this
