### ISSUE TITLE
Show locations in results on a country level

### ISSUE THREAD

**Issue by DonMeadows** [GreenDelta/olca-app#59]
Currently, when opening the _Locations_ tab upon calculating LCIA results the _hotspots_ are indicated by a circular shape with graduated color. Sometimes this can be misleading because most databases only allow to specify the location of impacts on a country level and not in more detail.
e.g. the hotspot indicator in the middle of the US does not mean that the impact is located at this specific spot in the US but rather that impacts occur _somewhere_ in the US. Maybe a more clear visualization would be to highlight the entire country if an impact occurs. Similar to this map of world economies by GDP: https://en.wikipedia.org/wiki/Gross_domestic_product#/media/File:Countries_by_GDP_(Nominal)_in_2014.svg

**Comment by msrocka** [comment]
this will be available in openLCA 2.0

![image](https://user-images.githubusercontent.com/3520062/99553885-eb1cf280-29be-11eb-9454-a4dfeeb821ad.png)
