### ISSUE TITLE
Monte Carlo Analysis results diverge from Impact results

### ISSUE THREAD

**Issue by DonMeadows** [GreenDelta/olca-app#60]
Under specific circumstances, the results of a Monte Carlo Analysis significantly diverge from the impact results. This has been described by an openLCA user on ask.openLCA.org https://ask.openlca.org/1186/monte-carlo-giving-widely-different-results-to-analysis

**Comment by msrocka** [comment]
Why is this a bug; can you give more details? Doesn't this depend on the distribution parameters and the resulting uncertainty distributions? -> Is there an error in the resulting distributions?

 You can test the distributions in the process editor and check if the resulting ranges are too high.
