### ISSUE TITLE
cannot download resolve dependencies

### ISSUE THREAD

**Issue by budongjimolin** [GreenDelta/olca-app#65]
![tim 20190124223618](https://user-images.githubusercontent.com/20294510/51685069-81349b80-2028-11e9-9f65-b059fb38cc49.jpg)

**Comment by msrocka** [comment]
You need to install the [olca-modules](https://github.com/GreenDelta/olca-modules) and [olca-updates](https://github.com/GreenDelta/olca-updates) libraries locally (via `mvn install`); they are not (yet) in the Maven Central
