### ISSUE TITLE
Bundle 'org.eclipse.fx.ui.workbench3' cannot be resolved

### ISSUE THREAD

**Issue by budongjimolin** [GreenDelta/olca-app#68]
![qq 20190130173621](https://user-images.githubusercontent.com/20294510/51972067-96407d00-24b5-11e9-9a7a-db8535eaa7f5.png)

**Comment by msrocka** [comment]
Unfortunately, the links in the target platform definition get quickly outdated (you can find the current version by following the respective update sites, e.g. https://download.eclipse.org/eclipse/updates); there is often a link `show directory content` with which you can browse the content). Updating a target definition is [very slow]( https://stackoverflow.com/q/38267514). The bundles are cached in your workspace but reading and synchronizing this cache takes forever…

I just setup a target platform with the current Eclipse version which seems to work:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><?pde version="3.8"?><target name="platform" sequenceNumber="6">
<locations>
  <location path="${eclipse_home}" type="Profile"/>
  <location includeAllPlatforms="true" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
    <unit id="org.eclipse.equinox.sdk.feature.group" version="3.14.0.v20180518-2029"/>
    <unit id="org.eclipse.rcp.feature.group" version="4.8.0.v20180611-0656"/>
    <repository location="http://download.eclipse.org/eclipse/updates/4.8"/>
  </location>
  <location includeAllPlatforms="true" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
    <unit id="org.eclipse.gef.all.feature.group" version="3.11.0.201606061308"/>
    <repository location="http://download.eclipse.org/tools/gef/updates/legacy/releases/"/>
  </location>
  <location includeAllPlatforms="true" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
    <unit id="org.eclipse.fx.ide.basic.feature.feature.group" version="3.4.1.201810030906"/>
    <unit id="org.eclipse.fx.ide.pde.feature.feature.group" version="3.4.1.201810030906"/>
    <repository location="http://download.eclipse.org/efxclipse/updates-released/3.4.1/site"/>
  </location>
  <location includeAllPlatforms="true" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
    <unit id="org.eclipse.babel.nls_eclipse_bg.feature.group" version="4.8.0.v20190126080931"/>
   <unit id="org.eclipse.babel.nls_eclipse_de.feature.group" version="4.8.0.v20190126080931"/>
   <unit id="org.eclipse.babel.nls_eclipse_es.feature.group" version="4.8.0.v20190126080931"/>
   <unit id="org.eclipse.babel.nls_eclipse_fr.feature.group" version="4.8.0.v20190126080931"/>
   <unit id="org.eclipse.babel.nls_eclipse_it.feature.group" version="4.8.0.v20190126080931"/>
   <unit id="org.eclipse.babel.nls_eclipse_pt.feature.group" version="4.8.0.v20190126080931"/>
   <unit id="org.eclipse.babel.nls_eclipse_tr.feature.group" version="4.8.0.v20190126080931"/>
   <unit id="org.eclipse.babel.nls_eclipse_zh.feature.group" version="4.8.0.v20190126080931"/>
   <repository location="https://download.eclipse.org/technology/babel/update-site/R0.16.1/photon"/>
  </location>
</locations>
</target>
```

Related issues:

* #71 macOS build
* #64 remove JavaFX dependencies (the `org.eclipse.fx.ui.workbench3` bundle from the efxclipse project is only required for JavaFX)

**Comment by Gaetan-Collin** [comment]
Hello, 

Setting this new target platform fixes the plugin-problem org.eclipse.fx.ui.workbench3 . However, when launching openLCA.product, i get the following exception:  

Unable to create class 'org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor' from bundle '675'
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javafx/scene/Parent

**Comment by msrocka** [comment]
@Gaetan-Collin did you add the [JavaFX bridge to your JRE config as described in the README](https://github.com/GreenDelta/olca-app#add-the-javafx-swt-bridge)?

also, there will be probably other problems with the platform config above -> there are currently some runtime dependencies that fail to load. This is why this issue is still open.

**Comment by Gaetan-Collin** [comment]
@mscrocka yes, i already added it.

**Comment by Gaetan-Collin** [comment]
I'm using Eclipse IDE for RCP and RAP Developers, Version: 2018-12 (4.10.0)

Which Eclipse version can I use to avoid these problems?

**Comment by msrocka** [comment]
The branch `e19-3` contains a product and target platform configuration that works with the Eclipse
19-03 release. Details about the changes can be found in this commit log: https://github.com/GreenDelta/olca-app/commit/b10b96174051445c2e05116dc5fa215e6ddef8c6

Also, I removed a lot of plug-in dependencies which makes the applicatoin start now much faster. The plan is to merge this into the master for the 1.9 release ... but this still needs more testing (also regarding issue #71).

**Comment by msrocka** [comment]
I merged the `e19-3` branch into the `master` which should fix these issues (when you use the current Eclipse 19-03 release)
