### ISSUE TITLE
Use jblas for fast matrix computation

### ISSUE THREAD

**Issue by NicolasDumoulin** [GreenDelta/olca-app#7]
Hello,

Do you have assess the use of the jblas library that promises high performance for matrix computation?
https://github.com/mikiobraun/jblas
https://mikiobraun.github.io/jblas/javadoc/index.html

**Comment by NicolasDumoulin** [comment]
Ok, I've discovered that you already use lapack :-)
Good job!

**Comment by msrocka** [comment]
Just as additional information: We use [OpenBLAS](http://www.openblas.net/) as high performance math library. We also have sparse matrix math bindings to [Eigen](http://eigen.tuxfamily.org) which are still experimental. The JNI bindings for this and compile instructions can be found in the [olca-eigen](https://github.com/GreenDelta/olca-modules) module.
