### ISSUE TITLE
Improve the build process

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/olca-app#71]
### Problem

Currently, we have two methods for building the application packages. The first method is to just export the application using the PDE export from the Eclipse user interface and then to run some packager scripts written in Python to embed things like the Java runtime, calculation libraries etc. and to create the final installers. This method uses a platform definition (`olca-app/platform.target`) that points to some remote p2-repositories for loading the components for cross platform builds (described as "the preferred way for multi-platform builds" in the [Eclipse wiki]( https://wiki.eclipse.org/A_Brief_Overview_of_Building_at_Eclipse#Preferred_way_of_doing_multi-platform_builds)). Configuring this platform definition has its own quirks but, when it is done and all the referenced components are in the bundle cache, it seems to be very stable and the build is easy then.

However, the PDE export has a major issue: [it does not create the macOS package correctly]( https://bugs.eclipse.org/bugs/show_bug.cgi?id=468131). Thus, for the macOS package we use our old build which is based on a platform definition (`olca-runtime/platform.target`) that points to local folders that contain all components. There is an Ant script that fetches these components from the respective websites. It is based on the [DeltaPack]( https://wiki.eclipse.org/A_Brief_Overview_of_Building_at_Eclipse#Old_way_of_using_the_.22DeltaPack.22) which allows multi-platform builds. But since Eclipse 4.5, the DeltaPack is not provided anymore and we have to stick to the 4.4 platform which is already quite outdated.

### Options

We should get rid of the old DeltaPack based build. Maybe we could find a quick fix for the PDE export based build that works on macOS (there are some hints in the comments of the [corresponding bug report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=468131) e.g. [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=468131#c57)). We could have some specific configuration for a macOS specific build.

However, the PDE export probably will never get updates again and when we do not find a quick fix we should try to switch to [Tycho]( http://www.vogella.com/tutorials/EclipseTycho/article.html) which is now the recommended way to build Eclipse based applications. Tycho can be configured to use the same platform definitions (with links to remote p2-repos) and configuration as the PDE based build (so we could have both). However, it requires changes in the project layout and quite some configuration. Unfortunately, the Tycho documentation is not so user friendly (super complex examples which do something where it is not obvious for what it is useful)…

**Comment by johnkazer** [comment]
How many macOS users do you have relative to the total? Maybe just drop it...
Then you can suggest macOS users run Ubuntu in a VM, dual-boot or similar?

At least it would keep you going without too much technical risk - just user risk :-(

**Comment by msrocka** [comment]
@johnkazer I think we have something between 10% and 15% mac users (the [statistics from our SourceForge archive](https://sourceforge.net/projects/openlca/files/stats/os?dates=2007-02-12+to+2019-02-11) are similar to the download statistics from the official openLCA website) -> so quite some users (the rest is mainly Windows; Linux is < 1% on our website)

**Comment by msrocka** [comment]
we have now a new build process based on the PDE export that works for all platforms
