### ISSUE TITLE
Integrated spread sheet editor

### ISSUE THREAD

**Issue by DonMeadows** [GreenDelta/olca-app#73]
Sometimes, working with parameters (actually applying formulas) in the amount field is confusing and cumbersome simply because of the small size of the amount field and the bad overview which this offers.
Instead, maybe it would be nice to have an integrated spreadsheet (e.g. accessible via a tab when opening a process) in which calculations can be performed and to which can be referred from the amount field. Via copy and paste, this would probably also further improve the compatibility with e.g. Microsoft Excel or LibreOfice Calc.
Possibly, this could either replace parameter or the parameter overview could simply be turned into a spreadsheet-like tab.

A similar approach is available e.g. in FreeCAD https://www.freecadweb.org/wiki/Spreadsheet_Workbench

**Comment by johnkazer** [comment]
I have had success with this javascript package in the browser but I don’t know if it is what you would want!
https://www.npmjs.com/package/canvas-datagrid
