### ISSUE TITLE
Changes in parameter overview not picked up by collab server

### ISSUE THREAD

**Issue by bl-young** [GreenDelta/olca-app#74]
When parameters are edited in the new parameter overview feature (v1.8), these changes do not trigger an update when committing to the collaboration server.  This occurs whether the change is made on a value or a formula. It appears as though the changes do not trigger an udpate to the version or "Last Change" on the process and therefore the collaboration server is not identifying anything to commit.

**Comment by msrocka** [comment]
It was even a bit more complicated than I first thought. If it is a global parameter it is fine to just update the `version` and `lastChange` fields. However, when it is a parameter in a process or LCIA method we also need to update this entity to which the parameter belongs.

Also, when a global parameter or the entity to which a parameter belongs is currently edited in another editor it should not be possible to modify that parameter from the parameter overview.

I hope this is fixed now. We will release it with the next version.
