### ISSUE TITLE
Enhanced copy and paste for improved handling/creation of LCIA methods

### ISSUE THREAD

**Issue by ghost** [GreenDelta/olca-app#76]
To better/more easily alter/change/create LCIA methods it would be very powerful if some additional drag and drop/copy and paste features would be implemented :)
1) From an "Impact factors" tab of an LCIA method into another "Impact factors" tab of another LCIA method
2) From the "Inventory results" tab of the calculation results of a product system into the "Impacts factors" tab of an LCIA method
3) From the "LCIA Checks" tab of the calculation results of a product system into the "Impact factors" tab of an LCIA method

**Comment by msrocka** [comment]
Maybe one idea to explore is maybe to add our JSON-LD format as clipboard format in addition to the current table based format. With this, we could exchange data between the tables in a more structured way.
