### ISSUE TITLE
GTK3 support in linux for 1.9

### ISSUE THREAD

**Issue by tngTUDOR** [GreenDelta/olca-app#85]
## Current
openlca 1.9.0 does not work under linux when trying to use GTK3.

An error message appears on the console as follows regarding GTK3:
```java
OpenLCA:
The OpenLCA executable launcher no longer supports running with GTK + 2.x. Continuing using GTK+ 3.x.
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
Log-level=INFO
0 [main] INFO org.openlca  - Log-level=INFO
Try to load Julia libs and bindings from /home/jkrolling/workspaces/openlca/1.9/openLCA
10 [main] INFO org.openlca.julia.Julia  - Try to load Julia libs and bindings from /home/jkrolling/workspaces/openlca/1.9/openLCA
No native libraries found
11 [main] INFO org.openlca.julia.Julia  - No native libraries found
Julia libraries could not be loaded from /home/jkrolling/workspaces/openlca/1.9/openLCA
11 [main] INFO org.openlca.app.App  - Julia libraries could not be loaded from /home/jkrolling/workspaces/openlca/1.9/openLCA
failed to load jblas-library: /home/jkrolling/openLCA-data-1.4/olca-eigen_0.3/Linux/amd64/libolca-eigen.so: libgfortran.so.3: cannot open shared object file: No such file or directory
13 [main] INFO org.openlca.eigen.NativeLibrary  - failed to load jblas-library: /home/jkrolling/openLCA-data-1.4/olca-eigen_0.3/Linux/amd64/libolca-eigen.so: libgfortran.so.3: cannot open shared object file: No such file or directory
could not load a high-performance library for calculations
13 [main] WARN org.openlca.app.App  - could not load a high-performance library for calculations
initialize Python interpreter
16 [Worker-0: init. Python] INFO org.openlca.app.devtools.python.Python  - initialize Python interpreter
FXModuleClassloader#findLocalClass - Failed to check for Gtk3
java.lang.NoSuchFieldException: GTK3
        at java.lang.Class.getDeclaredField(Class.java:2070)
        at org.eclipse.fx.osgi.fxloader.FXClassLoader$SWTFXClassloader.findClass(FXClassLoader.java:839)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.eclipse.fx.osgi.fxloader.FXClassLoader.postFindClass(FXClassLoader.java:135)
        at org.eclipse.osgi.internal.loader.BundleLoader.searchHooks(BundleLoader.java:527)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:490)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.openlca.app.search.SearchText.createControl(SearchText.java:55)
...
```
The main application window appears, but elements are unclickable (menus and buttons).

It seems like GTK-3 support for openjdk 1.8 has only been added on release 202:

[Release Note: GTK3 Supported on Linux](https://bugs.openjdk.java.net/browse/JDK-8213485)

So, as of openlca I think this is a bug preventing version 1.9 to run properly in linux.

## Expected
openlca 1.9 runs fine on linux with gtk3

**Comment by tngTUDOR** [comment]
@msrocka So that we can help further with this issue, can you provide a little insight of why:
> Note that openLCA currently only correctly works with a JRE 8u101.
 https://github.com/GreenDelta/olca-app/tree/master/olca-app-build

**Comment by msrocka** [comment]
Mainly because there is an error in the JavaFX webview in newer JRE versions that causes that mouse events get lost in the JavaFX-SWT bridge...

I am currently replacing JavaFX with plain SWT widgets (see the `nofx` branch and this issue https://github.com/GreenDelta/olca-app/issues/64). With these updates, I hope I can also update to the current JRE 8 (u22) provided by https://adoptopenjdk.net/.

Note that openLCA comes with an embedded JRE on all platforms. To test things, you can simply replace the content of the `jre` folder with another JRE.

**Comment by crocodile2u** [comment]
Apparently, JRE 8u101 is not available for download at https://adoptopenjdk.net/. Also wanted to say it's gonna help a lot if this GTK3 bug is fixed, and things just run smoothly on Linux.. 

I tried with Oracle Java 12 (just replaced the jre folder), the interface starts up but is unusable :(

Anyways, thanks for the great job, fellas!

**Comment by msrocka** [comment]
@crocodile2u correct. I will integrate JRE 8u222-b10. So far the current master looks good also on Linux (at least on Ubuntu 18.04, this is what I tested). We will provide first test builds with this on the openLCA website beginning of next week.

**Comment by tngTUDOR** [comment]
I just ran the app from within eclipse using the little fix of: https://github.com/GreenDelta/olca-app/pull/94 and I can confirm that the app works. I haven't done thorough testing, only looked at a 

I used 

- current master branch
- java-1.8.0-openjdk-1.8.0.222.b10 - from Fedora 30
- gtk3: 3.24.11-1.fc30.x86_64
- eclipse
```
Eclipse IDE for RCP and RAP Developers

Version: 2019-09 R (4.13.0)
Build id: 20190917-1200
```

**Comment by msrocka** [comment]
I uploaded a first test build to the openLCA website:

http://www.openlca.org/download/  > Latest build > Linux version

It packages the current JRE 8 from [AdoptOpenJDK.net](https://adoptopenjdk.net/). Also, it includes the native math libraries from https://github.com/msrocka/olca-rust (see #28). In the log (Help > Log file) there should be some information that these libraries are loaded:

```
...
loaded native library ... libolcar.so
Math library loaded ...
```

It works for me ... just post to this issue or open a new one when there is still something wrong. Thanks.

**Comment by crocodile2u** [comment]
I confirm that it works like a charm now! Many thanks!
