### ISSUE TITLE
Share parameter in Contribution item 

### ISSUE THREAD

**Issue by Gaetan-Collin** [GreenDelta/olca-app#89]
Hi,

I need to know the meaning of the share parameter in the contributionItem class and if it is usefull to get the contribution tree  for a given category impact.

Thank you in advance,
best regards,
Karima.

**Comment by msrocka** [comment]
In a `ContributionItem`, `amount` is the absolute and `share` the relative  value of the respective contribution (e.g. a contribution of a flow to a LCIA category result).

For building contribution trees you can use the `org.openlca.core.results.UpstreamTree` class.
