### ISSUE TITLE
Add a function like `Reset window layout`

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/olca-app#97]
For example, detaching the navigation pane and moving it back sometimes breaks the window layout which cannot be reverted; see https://ask.openlca.org/2082/openlca-window-veiw

Currently, the only way to reset the window layout is to delete this file `.../openLCA-data-1.4/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi` in your user folder.

But there should be a function in openLCA for this. It could just delete this file and reopen openLCA as a quick fix.

**Comment by rurudipper** [comment]
For version 1.10.3, we can choose "reset the window layout" under tab "configutation".
